#!bin/bash
#This is the Mid-Term assignment
#MY name is- Mansidak Singh
#Student ID - 200359733

#Define command line help.
function help {
  cat <<EOF
  Usage: $0
  [-h | --help ] [-n | --netinfo] [-i | --ipinfo]  [-o | --osinfo]  [-c | --cpuinfo][-m | --memoinfo]  [-d | --diskinfo]  [-p | --printinfo]  [-s | --software]
EOF
}

function errormessage {
  echo "$@" >&2

}

rdefault="good"
while [ $# -gt 0 ]; do
case "$1" in
-h| --help )
displayhelp
rdefault="bad";;
-n| --netinfo)
netinfo="good"
rdefault="bad"
export netinfo ;;
-i| --ipinfo)
ipinfo="good"
rdefault="bad" export ipinfo
;;
-o| --osinfo)
osinfo="good"
rdefault="bad"
;;
-c| --cpuinfo)
cpuinfo="good"
rdefault="bad"
;;
-m| --meminfo)
meminfo="good"
rdefault="bad"
export meminfo ;;
-d| --diskinfo)
diskinfo="good"
rdefault="bad"
;;
-p| --printinfo)
printinfo="good"
rdefault="bad"
export printinfo

;;
-s| --software)
software="good"
rdefault="bad"
export software and rdefault;;
*)
errormessage "Case '$1' badt recognised."
errormessage "$(displayhelp)" exit 1 ;;
esac
shift
done
osinfo="$(grep PRETTY /etc/os-release |sed -e 's/.*=//' -e 's/"//g')"
# following shows System and domain name
if [[ "$rdefault" = "good" || "$netinfo" = "good" ]]; then
myhostname="$(hostname)"
domainname="$(hostname -d)"


cat <<EOF
# using variables for output
############################ Net Info ############################

Hostname: $myhostname
Domain: $domainname
EOF
fi

# IP addresses for the host Info
if [[ "$rdefault" = "good" || "$ipinfo" = "good" ]]; then
echo "############################ IP Info ############################="
  interfaces=(`ifconfig |grep '^[A-Za-z]'|awk '{print $1}'`) # an array of interface names configured on this machine
  numinterfaces=${#interfaces[@]}
  declare -A ips # will be a hash with ip addresses, keyed using interface name
  intfindex=0 # will be used to iterate over the interfaces array

  while [ $intfindex -lt $numinterfaces ]; do
  # grabing name from the interfaces array
    intfname="${interfaces[$intfindex]}"
  # extract the assigned ip address using ifconfig and storing in ips hash
    ips[$intfname]="`ifconfig $intfname|grep 'inet '|sed -e 's/.*addr://' -e 's/ .*//'`"

  # FOllowing displays the interface and its ip addresses
    if [ -n "${ips[$intfname]}" ]; then
      echo "  Interface $intfname has the address ${ips[$intfname]}"
    else
      echo "  Interface $intfname has bad ip address"
    fi
  # adding the index and move to the next interfaces array value
    intfindex+=1
  done
  echo ""
fi

domainname="$(grep PRETTY /etc/os-release |sed -e 's/.*=//' -e 's/"//g')"
export domainname
# OS name and version
if [[ "$rdefault" = "good" || "$osinfo" = "good" ]]; then
  osinformation="$(grep PRETTY /etc/os-release | sed -e 's/.*=//' -e 's/\"//g')"

cat <<EOF
############################ OS Info ############################
  OS Info: $osinformation
EOF
fi

# Central Processing Unit description of the system
if [[ "$rdefault" = "good" || "$cpuinfo" = "good" ]]; then
  echo "############################ CPU Details ############################"
  lscpu | grep "Model name:"
  echo ""
fi

# Installed Memory on the system
if [[ "$rdefault" = "good" || "$meminfo" = "good" ]]; then
echo "############################ Total Memory ############################"
  cat /proc/meminfo | grep MemTotal
echo ""
fi

# Available Disk Space on current system
if [[ "$rdefault" = "good" || "$diskinfo" = "good" ]]; then
  echo "############################Disk Space ############################"
  df -h
  echo ""
fi

# List of Printers on the system
if [[ "$rdefault" = "good" || "$printinfo" = "good" ]]; then
  echo "############################Printers ############################="
  lpstat -p
  echo ""
fi

# following Softwares are installed on the system
if [[ "$rdefault" = "good" || "$software" = "good" ]]; then
  echo "############################ Installed Software ############################"
  apt list --installed
  echo ""
fi

#*************END***************S
